-- Admin Site Management Table
CREATE TABLE ADMIN_SITE_MANAGEMENT (
    siteId VARCHAR(255) PRIMARY KEY NOT NULL,
    siteName VARCHAR(255) NOT NULL,
    siteDomain VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    topLogoImage VARCHAR(255),
    bottomLogoImage VARCHAR(255),
    mainImage VARCHAR(255),
    siteDescription VARCHAR(1000),
    mouseSecurity BOOLEAN,
    keyboardSecurity BOOLEAN,
    createdBy VARCHAR(255)
);

-- Admin Terms Management Table
CREATE TABLE ADMIN_TERMS_MANAGEMENT (
    termsId VARCHAR(255) PRIMARY KEY NOT NULL,
    studentTerms TEXT,
    staffTerms TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    effectiveDate TIMESTAMP NOT NULL,
    createdBy VARCHAR(255)
);

-- Admin Common Codes Table
CREATE TABLE ADMIN_COMMON_CODES (
    codeId VARCHAR(255) PRIMARY KEY NOT NULL,
    categoryCode VARCHAR(255) NOT NULL,
    codeName VARCHAR(255) NOT NULL,
    codeDescription VARCHAR(1000),
    active BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdBy VARCHAR(255)
);

-- Admin Sub Common Codes Table
CREATE TABLE ADMIN_SUB_COMMON_CODES (
    subCodeId VARCHAR(255) PRIMARY KEY NOT NULL,
    codeId VARCHAR(255) NOT NULL,
    subCodeName VARCHAR(255) NOT NULL,
    codeDescription VARCHAR(1000),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdBy VARCHAR(255),
    FOREIGN KEY (codeId) REFERENCES ADMIN_COMMON_CODES(codeId) ON DELETE CASCADE
);

-- Admin IP Table
CREATE TABLE ADMIN_IP_TABLE (
    allowedIp VARCHAR(255) PRIMARY KEY NOT NULL,
    adminId VARCHAR(255) NOT NULL,
    active BOOLEAN,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdBy VARCHAR(255),
    FOREIGN KEY (adminId) REFERENCES USER_TABLE(userId) ON DELETE CASCADE
);

-- Admin User Table
CREATE TABLE ADMIN_USER_TABLE (
    userId VARCHAR(255) PRIMARY KEY NOT NULL,
    userSeCode VARCHAR(255) NOT NULL,
    userName VARCHAR(255) NOT NULL,
    userPw VARCHAR(255) NOT NULL,
    userRole VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(255),
    emailAddress VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    grade VARCHAR(255),
    className VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);